version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      #- run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
       # run tests!
      #- run: gradle test - enable when tests needs to be done

         
  Build_Jar:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: export TERM=xterm && ./gradlew bootJar
      - run: ls build/libs/
      - run: scp -r -o StrictHostKeyChecking=no build/libs/ vinod@server1.tvizion.site:/home/vinod
      - run: sudo apt update # && sudo apt install golang-1.11-go
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - Build_Jar:
#          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
