version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      #- run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
          
  Check_Jar:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: export TERM=xterm && ./gradlew bootJar
      - run: ls build/libs
      - run: sudo apt update
      - run: sudo add-apt-repository ppa:gophers/archive && sudo apt update && sudo apt install golang-1.11-go
 #     - run: wget https://dl.google.com/go/go1.13.3.linux-amd64.tar.gz
 #     - run: tar -xvf go1.13.3.linux-amd64.tar.gz && sudo mv go /usr/local
      - run: export GOPATH=~/go
 #     - run: export GOPATH=$HOME/repo
 #     - run: export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs
          
  push_Jar:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.13rc1-buster
    steps:
      - checkout      
      - run: export TERM=xterm && ./gradlew bootJar
      - run: go get -u github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs
#      - run: 
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - Check_Jar:
          requires:
            - build

      - push_Jar:
          requires:
            - Check_Jar
