version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      #- run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
       # run tests!
      #- run: gradle test - enable when tests needs to be done

         
  Build_and_push_Jar:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
#      - image: circleci/golang:1.13.6-buster
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo apt-get -y -qq update
      - run: export TERM=xterm && ./gradlew bootJar
      - run: ls build/libs/           
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - Build_and_push_Jar:
          requires:
            - build
