version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      #- run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
       # run tests!
      #- run: gradle test - enable when tests needs to be done

         
  Build_and_push_Jar:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
#      - image: circleci/golang:1.13.6-buster
    steps:
      - checkout
      - run: sudo apt-get -y -qq update
      - run: export TERM=xterm && ./gradlew bootJar
      - run: ls build/libs/
      - run: sudo apt-get -y -qq update
      - run: sudo apt-get -y install curl
      - run: curl -0 https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz --output go1.13.8.linux-amd64.tar.gz
      - run: tar -xvf go1.13.8.linux-amd64.tar.gz
      - run: sudo mv go /usr/local
      - run: echo 'export GOPATH=$HOME/go' >> ~/.bashrc
      - run: echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin' >> ~/.bashrc
      - run: source ~/.bashrc
      - run: go get -u github.com/tcnksm/ghr

#      - run: scp -r -o StrictHostKeyChecking=no build/ user@server:/home/user
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - Approve:
#          requires:
#            - build
#          type: approval
      - Build_and_push_Jar
#          requires:
#            - Approve
          #type: approval
#          filters:
#            branches:
#              only: master
